import { Note as NoteModel } from "@prisma/client";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "./card";

//renamed to NoteModel to avoid conflict with the Note component
//note is autogenerated by prisma and contains the note data
interface NoteProps {
  note: NoteModel;
}

//destructuring the note from the props
export default function Note({ note }: NoteProps) {
  // check if the note was updated or not
  const wasUpdated = note.updatedAt > note.createdAt;
  // get the created or updated at timestamp
  const createdUpdatedAtTimestamp = (
    wasUpdated ? note.updatedAt : note.createdAt
  ).toDateString();

  return (
    <Card>
      <CardHeader>
        <CardTitle>{note.title}</CardTitle>
        <CardDescription className="text-xs">
          {createdUpdatedAtTimestamp}
          {wasUpdated && " (Updated)"}
          {/* if the note was updated, display the updated string */}
        </CardDescription>
      </CardHeader>
      <CardContent>
        {/* preline displays all line breaks etc */}
        <p className="whitespace-pre-line">{note.content}</p>
      </CardContent>
    </Card>
  );
}
